#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TIME_STEP 10
#define SPEED_ADUSTING_CONSTANT 1
#define NORMAL_SPEED 170
#define CARCAR_NAME "HM10_G6"
#define LEAVE_NODE_THRESHOLD (-1.50)

#endif // CONSTANTS_H
