import sys
import time

from hm10_esp32 import HM10ESP32Bridge
from score import ScoreboardServer

# === Project Environment Settings ===
PORT = 'COM7'
EXPECTED_NAME = 'HM10_G6'
TEAM_NAME = "食致銘龜"
SERVER_URL = "http://carcar.ntuee.org/scoreboard"

# The optimal continuous scoring path generated by your algorithm
BFS_RESULT = "FFLFBFRRLRALLFRAF"
WINDOW_SIZE = 3

def execute_auto_path(bridge, path_string, point):
    commands = list(path_string.upper())
    total_steps = len(commands)
    sent_idx = 0
    ack_count = 0
    
    # Record visited UIDs to prevent network congestion
    visited_uids = set()

    print("\n" + "="*40)
    print(f"Starting fully automated continuous scoring mission!")
    print(f"Total steps: {total_steps}")
    print("="*40)

    # 1. Initial Fill: Send the first 3 commands to the car
    for _ in range(WINDOW_SIZE):
        if sent_idx < total_steps:
            bridge.send(commands[sent_idx])
            print(f"[SEND] Initial command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
            sent_idx += 1
            time.sleep(0.1)

    # 2. Enter Sliding Window Listener Loop
    while ack_count <= total_steps:
        msg = bridge.listen()
        
        # Process any received signal immediately
        if msg:
            msg = msg.strip()
            
            if not msg:
                continue # Skip empty lines
            
            # --- Case A: Received Step ACK from Car ---
            if "NX" in msg:
                ack_count += 1
                print(f"\n[PROGRESS] Node reached, completed step {ack_count}")
                
                if sent_idx < total_steps:
                    bridge.send(commands[sent_idx])
                    print(f"[SEND] Next command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
                    sent_idx += 1
                    
            # --- Case B: Received RFID UID from Car ---
            elif "UID:" in msg:
                clean_uid = msg.replace("UID:", "").replace(" ", "").strip()
                
                # Prevent fragmentation: take only the first 8 chars
                if len(clean_uid) > 8:
                    clean_uid = clean_uid[:8]
                
                # Filter fragments: skip if shorter than 8 chars
                if len(clean_uid) < 8:
                    print(f"Warning: UID length incorrect ({len(clean_uid)} chars). Skipped.")
                    print(f"Received: {msg}")
                    continue
                
                # Anti-spam: skip if this card was already scored
                if clean_uid in visited_uids:
                    continue 

                # Upload valid new card
                if len(clean_uid) == 8:
                    print(f"\n[RFID] Treasure found! Read UID: {clean_uid}")
                    try:
                        current_score, time_left = point.add_UID(clean_uid)
                        # point.add_UID("53FE3C31")
                        # point.add_UID("5205171E")
                        # point.add_UID("9AC053BD")
                        # point.add_UID("F159AF1E")
                        # point.add_UID("00000000")
                        # point.add_UID("11111111")
                        # point.add_UID("22222222")
                        # point.add_UID("33333333")
                        # point.add_UID("44444444")
                        # point.add_UID("55555555")
                        # point.add_UID("66666666")
                        # point.add_UID("77777777")
                        # point.add_UID("88888888")
                        # point.add_UID("99999999")
                        # point.add_UID("AAAAAAAA")
                        # point.add_UID("BBBBBBBB")
                        # point.add_UID("CCCCCCCC")
                        # point.add_UID("DDDDDDDD")
                        # point.add_UID("EEEEEEEE")
                        # point.add_UID("FFFFFFFF")
                        # point.add_UID("GGGGGGGG")
                        # point.add_UID("HHHHHHHH")
                        # point.add_UID("IIIIIIII")
                        # point.add_UID("JJJJJJJJ")
                        # point.add_UID("10BA617E")
                        # point.add_UID("84EAB017")
                        # point.add_UID("50335F7E")
                        # point.add_UID("353D0AD6")
                        # point.add_UID("556D04D6")
                        # point.add_UID("C59B51D0")
                        print(f"Server Response -> Current Score: {current_score}, Time Left: {time_left}s")
                        
                        # Add to visited set after successful upload
                        visited_uids.add(clean_uid) 
                    except Exception as e:
                        print(f"Failed to upload score: {e}")
                    
            # --- Case C: Other messages from Car ---
            else:
                print(f"[CAR] {msg}")
                
        time.sleep(0.01)

    print("\n" + "="*40)
    print("All path commands executed successfully!")
    print("="*40 + "\n")

def main():
    bridge = HM10ESP32Bridge(port=PORT)
    
    # 1. Configuration Check
    current_name = bridge.get_hm10_name()
    if current_name != EXPECTED_NAME:
        print(f"Target mismatch. Current: {current_name}, Expected: {EXPECTED_NAME}")
        print(f"Updating target name to {EXPECTED_NAME}...")
        
        if bridge.set_hm10_name(EXPECTED_NAME):
            print("Name updated successfully. Resetting ESP32...")
            bridge.reset()
            # Re-init after reset
            bridge = HM10ESP32Bridge(port=PORT)
        else:
            print("Failed to set name. Exiting.")
            sys.exit(1)

    # 2. Connection Check
    status = bridge.get_status()
    if status != "CONNECTED":
        print(f"ESP32 is {status}. Please ensure HM-10 is advertising. Exiting.")
        sys.exit(0)

    print(f"Ready! Connected to {EXPECTED_NAME}")
    
    # 3. Initialize Scoreboard Server
    print("Connecting to the competition server...")
    # point = ScoreboardServer(TEAM_NAME, SERVER_URL)

    # 4. Start Auto-Navigation and Scoring
    try:
        execute_auto_path(bridge, BFS_RESULT, 0)
    except KeyboardInterrupt:
        print("\nUser interrupted. Sending emergency stop command...")
        bridge.send("S")
        
    print("\nMission complete. Connection closed.")

if __name__ == "__main__":
    main()
# import argparse
# import logging
# import sys
# import time

# from BTinterface import BTInterface
# from hm10_esp32 import HM10ESP32Bridge
# from maze import Action, Maze
# # === Import the TA's Scoreboard Module ===
# from score import ScoreboardServer

# # === Project Environment Settings ===
# PORT = 'COM5'
# EXPECTED_NAME = 'HM10_G6'
# TEAM_NAME = "Willy Yang"
# SERVER_URL = "http://carcar.ntuee.org/scoreboard"

# # The optimal continuous scoring path generated by your algorithm
# BFS_RESULT = "FFLFBFRRLRALLFRAF"

# # BFS_RESULT = "FFL" 
# # BFS_RESULT = "FFLFBFRRLRALLFRAF"
# WINDOW_SIZE = 3

# def execute_auto_path(bridge, path_string, point):
#     commands = list(path_string.upper())
#     total_steps = len(commands)
#     sent_idx = 0
#     ack_count = 0

#     print("\n" + "="*40)
#     print(f"Starting fully automated continuous scoring mission!")
#     print(f"Total steps: {total_steps}")
#     print("="*40)

#     # 1. Initial Fill: Send the first 3 commands to the car
#     for _ in range(WINDOW_SIZE):
#         if sent_idx < total_steps:
#             bridge.send(commands[sent_idx])
#             print(f"[SEND] Initial command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
#             sent_idx += 1
#             time.sleep(0.1)

#     # 2. Enter Sliding Window Listener Loop
#     while ack_count < total_steps:
#         msg = bridge.listen()
        
#         # Process any received signal immediately
#         if msg:
#             msg = msg.strip()
            
#             if not msg:     #No Messeages
#                 continue # Skip empty lines
            
#             # --- Case A: Received Step ACK from Car ---
#             if "NX" in msg:
#                 ack_count += 1
#                 print(f"\n[PROGRESS] Node reached, completed step {ack_count}")
                
#                 if sent_idx < total_steps:
#                     bridge.send(commands[sent_idx])
#                     print(f"[SEND] Next command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
#                     sent_idx += 1
                    
#             # --- Case B: Received RFID UID from Car ---
#             elif "UID:" in msg:
#                 # Clean the UID as we did before
#                 clean_uid = msg.replace("UID:", "").replace(" ", "").strip()
                
#                 # Extra Failsafe: Ensure it's exactly 8 characters before sending to server
#                 if len(clean_uid) == 8:
#                     print(f"\n[RFID] Treasure found! Read UID: {clean_uid}")
#                     try:
#                         current_score, time_left = point.add_UID(clean_uid)
#                         print(f"Server Response -> Current Score: {current_score}, Time Left: {time_left}s")
#                     except Exception as e:
#                         print(f"Failed to upload score: {e}")
#                 else:
#                     # Skip invalid packets to prevent crashes
#                     print(f"Warning: UID length incorrect ({len(clean_uid)} chars). Skipped: {clean_uid}")
                    
#             # --- Case C: Other messages from Car ---
#             else:
#                 print(f"[CAR] {msg}")
                
#         time.sleep(0.01)

#     print("\n" + "="*40)
#     print("All path commands executed successfully!")
#     print("="*40 + "\n")

# def main():
#     bridge = HM10ESP32Bridge(port=PORT)
    
#     # 1. Configuration Check
#     current_name = bridge.get_hm10_name()
#     if current_name != EXPECTED_NAME:
#         print(f"Target mismatch. Current: {current_name}, Expected: {EXPECTED_NAME}")
#         print(f"Updating target name to {EXPECTED_NAME}...")
        
#         if bridge.set_hm10_name(EXPECTED_NAME):
#             print("Name updated successfully. Resetting ESP32...")
#             bridge.reset()
#             # Re-init after reset
#             bridge = HM10ESP32Bridge(port=PORT)
#         else:
#             print("❌ Failed to set name. Exiting.")
#             sys.exit(1)

#     # 2. Connection Check
#     status = bridge.get_status()
#     if status != "CONNECTED":
#         print(f"ESP32 is {status}. Please ensure HM-10 is advertising. Exiting.")
#         sys.exit(0)

#     print(f"Ready! Connected to {EXPECTED_NAME}")
    
#     # 3. Initialize Scoreboard Server
#     print("Connecting to the competition server...")
#     point = ScoreboardServer(TEAM_NAME, SERVER_URL)

#     # 4. Start Auto-Navigation and Scoring
#     try:
#         execute_auto_path(bridge, BFS_RESULT, point)
#     except KeyboardInterrupt:
#         print("\nUser interrupted. Sending emergency stop command...")
#         bridge.send("S")
        
#     print("\nMission complete. Connection closed.")

# if __name__ == "__main__":
#     main()
