import argparse
import logging
import sys
import time

from BTinterface import BTInterface
from hm10_esp32 import HM10ESP32Bridge
from maze import Action, Maze
# === Import the TA's Scoreboard Module ===
from score import ScoreboardServer

# === Project Environment Settings ===
PORT = 'COM5'
EXPECTED_NAME = 'HM10_G6'
SERVER_URL = "http://carcar.ntuee.org/scoreboard"
TEAM_NAME = "Willy Yang"

# The optimal continuous scoring path generated by your algorithm
BFS_RESULT = "RBLBRBLBRBLB"
WINDOW_SIZE = 3

def execute_auto_path(bridge, path_string, point):
    commands = list(path_string.upper())
    total_steps = len(commands)
    sent_idx = 0
    ack_count = 0
    rx_buffer = ""

    print("\n" + "="*40)
    print(f"Starting fully automated continuous scoring mission!")
    print(f"Total steps: {total_steps}")
    print("="*40)

    for _ in range(WINDOW_SIZE):
        if sent_idx < total_steps:
            bridge.send(commands[sent_idx])
            print(f"[SEND] Initial command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
            sent_idx += 1
            time.sleep(0.1)

    while ack_count < total_steps:
        raw_msg = bridge.listen()
        
        if raw_msg:
            rx_buffer += raw_msg
            
            while '\n' in rx_buffer:
                line, rx_buffer = rx_buffer.split('\n', 1)
                msg = line.strip()
                
                if not msg:
                    continue
                
                if "STEP_DONE" in msg:
                    ack_count += 1
                    print(f"\n[PROGRESS] Node reached, completed step {ack_count}")
                    
                    if sent_idx < total_steps:
                        bridge.send(commands[sent_idx])
                        print(f"[SEND] Next command {sent_idx+1}/{total_steps}: {commands[sent_idx]}")
                        sent_idx += 1
                        
                elif "UID:" in msg:
                    clean_uid = msg.replace("UID:", "").replace(" ", "").strip()
                    
                    if len(clean_uid) == 8:
                        print(f"\n[RFID] Treasure found! Read UID: {clean_uid}")
                        try:
                            current_score, time_left = point.add_UID(clean_uid)
                            print(f"Server Response -> Current Score: {current_score}, Time Left: {time_left}s")
                        except Exception as e:
                            print(f"Failed to upload score: {e}")
                    else:
                        print(f"Warning: UID length incorrect ({len(clean_uid)} chars). Skipped: {clean_uid}")
                        
                else:
                    print(f"[CAR] {msg}")
                    
        time.sleep(0.01)

    print("\n" + "="*40)
    print("All path commands executed successfully!")
    print("="*40 + "\n")

def main():
    bridge = HM10ESP32Bridge(port=PORT)
    
    # 1. Configuration Check (Preserved your original Bluetooth check logic)
    current_name = bridge.get_hm10_name()
    if current_name != EXPECTED_NAME:
        print(f"Target mismatch. Current: {current_name}, Expected: {EXPECTED_NAME}")
        print(f"Updating target name to {EXPECTED_NAME}...")
        
        if bridge.set_hm10_name(EXPECTED_NAME):
            print("? Name updated successfully. Resetting ESP32...")
            bridge.reset()
            # Re-init after reset
            bridge = HM10ESP32Bridge(port=PORT)
        else:
            print("? Failed to set name. Exiting.")
            sys.exit(1)

    # 2. Connection Check
    status = bridge.get_status()
    if status != "CONNECTED":
        print(f"ESP32 is {status}. Please ensure HM-10 is advertising. Exiting.")
        sys.exit(0)

    print(f"? Ready! Connected to {EXPECTED_NAME}")
    
    # 3. Initialize Scoreboard Server
    print("Connecting to the competition server...")
    point = ScoreboardServer(TEAM_NAME, SERVER_URL)

    # 4. Start Auto-Navigation and Scoring
    try:
        execute_auto_path(bridge, BFS_RESULT, point)
    except KeyboardInterrupt:
        print("\nUser interrupted. Sending emergency stop command...")
        bridge.send("S")
        
    print("\nMission complete. Connection closed.")

if __name__ == "__main__":
    main()
# import sys
# import threading
# import time

# from hm10_esp32 import HM10ESP32Bridge
# from score import ScoreboardServer
# PORT = 'COM5'
# EXPECTED_NAME = 'HM10_G6'
# # ���] result �O BFS ��X�Ӫ����G "ffrlb"
# commands = list(result.upper()) # �ন�j�g�é ['F', 'F', 'R', 'L', 'B']
# sent_idx = 0     # �ثe�o�e����@��
# ack_count = 0    # ���l�w�g�^�������X��
# WINDOW_SIZE = 3  # ���l�w�s�j�p

# def background_listener(bridge):
#     while True:
#         msg = bridge.listen()
#         if msg:
#             print(f"\r[HM10]: {msg}")
#             print("You: ", end="", flush=True)
#         time.sleep(0.1)

# def main():
#     bridge = HM10ESP32Bridge(port=PORT)
    
#     # 1. Configuration Check
#     current_name = bridge.get_hm10_name()
#     if current_name != EXPECTED_NAME:
#         print(f"Target mismatch. Current: {current_name}, Expected: {EXPECTED_NAME}")
#         print(f"Updating target name to {EXPECTED_NAME}...")
        
#         if bridge.set_hm10_name(EXPECTED_NAME):
#             print("? Name updated successfully. Resetting ESP32...")
#             bridge.reset()
#             # Re-init after reset
#             bridge = HM10ESP32Bridge(port=PORT)
#         else:
#             print("? Failed to set name. Exiting.")
#             sys.exit(1)

#     # 2. Connection Check
#     status = bridge.get_status()
#     if status != "CONNECTED":
#         print(f"?? ESP32 is {status}. Please ensure HM-10 is advertising. Exiting.")
#         sys.exit(0)

#     print(f"? Ready! Connected to {EXPECTED_NAME}")
#     threading.Thread(target=background_listener, args=(bridge,), daemon=True).start()

#     try:
#         while True:
#             user_msg = input("You: ")
#             if user_msg.lower() in ['exit', 'quit']: break
#             if user_msg: bridge.send(user_msg)
#     except (KeyboardInterrupt, EOFError):
#         pass
    
#     print("\nChat closed.")

# if __name__ == "__main__":
#     main()